#!/usr/bin/env bash
currentdir=${PWD##*/}
export RACKSPACE_FOLDER=${RACKSPACE_FOLDER:=$currentdir}
export RACKSPACE_USERNAME=${RACKSPACE_USERNAME:=""}
export RACKSPACE_APIKEY=${RACKSPACE_APIKEY:=""}
export RACKSPACE_CONTAINER=${RACKSPACE_CONTAINER:=""}


for i in "$@"
do
case $i in
		-f=*|--folder=*)
    RACKSPACE_FOLDER="${i#*=}"
    ;;
    -u=*|--username=*)
    RACKSPACE_USERNAME="${i#*=}"
    ;;
    -a=*|--apikey=*)
    RACKSPACE_APIKEY="${i#*=}"
    ;;
    -c=*|--container=*)
    RACKSPACE_CONTAINER="${i#*=}"
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
done

if [[ ! -d $RACKSPACE_FOLDER ]]; then
	echo "$RACKSPACE_FOLDER does not exist"
	exit 1
fi

if [[ -z $RACKSPACE_USERNAME ]]; then
	echo "RACKSPACE_USERNAME needed"
	exit 1
fi

if [[ -z $RACKSPACE_APIKEY ]]; then
	echo "RACKSPACE_APIKEY needed"
	exit 1
fi

if [[ -z $RACKSPACE_CONTAINER ]]; then
	echo "RACKSPACE_CONTAINER needed"
	exit 1
fi

echo "FOLDER: $RACKSPACE_FOLDER"
echo "USER: $RACKSPACE_USERNAME"
echo "KEY: $RACKSPACE_APIKEY"
echo "CONTAINER: $RACKSPACE_CONTAINER"


function auth() {
	curl -s -d \
	'{
	    "auth":
	    {
	       "RAX-KSKEY:apiKeyCredentials":
	       {  
	          "username": "diggerhq",  
	          "apiKey": "a39bd9bf7884cec67477b2893732cd38"}
	    }  
	}' \
	-H 'Content-Type: application/json' \
	'https://identity.api.rackspacecloud.com/v2.0/tokens' | python -m json.tool
}

function upload_file() {
	curl -X PUT -T $ii -H "X-Auth-Token: ae2bb8ae06ed48f992b13cf185fc0d6e" "https://storage101.lon3.clouddrive.com/v1/MossoCloudFS_39a3ae15-8942-4307-a23c-79f681874d36/legacy_files/$ii";
}

function upload_folder() {
	for ii in `find ./ -type f -name '*'|cut -b 3-|grep -v -P '^$'`; do
		upload_file $ii
		if [[ ! -d /root/uploaded/$ii ]]; then
			curl -X PUT -T $ii -H "X-Auth-Token: ae2bb8ae06ed48f992b13cf185fc0d6e" "https://storage101.lon3.clouddrive.com/v1/MossoCloudFS_39a3ae15-8942-4307-a23c-79f681874d36/legacy_files/$ii";
			echo $ii
			mkdir -p /root/uploaded/$ii
		fi
	done

}